#This workflow uses actions that are not certified by GitHub.
#They are provided by a third-party and are governed by
#separate terms of service, privacy policy, and support
#documentation.
#This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
#For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  # Can be called by another workflow
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab (only runs on the default branch)
  workflow_dispatch:

# Defines concurrent policies for the workflow, for example, if a commit is made while
# the workflow is running, should the current run be cancelled or should the new run be queued
# Docs: https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          # js (both node and browser)
          - target: jsTest
            os: ubuntu-latest
          # jvm
          - target: jvmTest
            os: ubuntu-latest
          # android
          - target: testDebugUnitTest
            os: ubuntu-latest
          - target: testReleaseUnitTest
            os: ubuntu-latest
          # native (depends on the host OS)
          - target: nativeTest
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@ce999babab2de1c4b649dc15f0ee67e6246c994f
      with:
        arguments: ${{ matrix.target }}
